name: perfection_task
description: "This is job task for perfection company"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable:
  flutter_svg: any
  http:
  internet_connection_checker:
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: any
  firebase_storage: any
  uuid:
  get_it:
  dartz:
  auto_size_text:
  dio:
  easy_localization:
  flutter_bloc:
  bloc:
  image_picker:
  cupertino_icons: ^1.0.6
  shared_preferences: any
  get:
  form_validator:
  carousel_slider:
  smooth_page_indicator:
  chat_gpt_flutter: ^1.0.16
  expandable_page_view:
  device_preview_minus:
  fluttertoast:
  flutter_stripe:
  flutter_secure_storage:
  google_sign_in:
  badges:
  flutter_native_splash: any
  googleapis: any
  googleapis_auth: any
  flutter_rating_bar:
  number_pagination: any
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf

  assets:
    - assets/fonts/
    - assets/translations/
    - assets/
    - assets/images/
